[package]
name = "omega_strikers_pairing"
version = "0.1.0"
edition = "2021"

[dependencies]
color-print = "0.3.6"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
uuid = { version = "1.10.0", features = ["v4"] }
